# Generated by Django 4.0.3 on 2022-03-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, null=True)),
                ('lastname', models.CharField(max_length=50, null=True)),
                ('Username', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(blank=True, default='xyz', max_length=50, null=True)),
                ('confirmPassword', models.CharField(blank=True, default='xyz', max_length=50, null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('pincode', models.IntegerField()),
                ('profileImg', models.FileField(null=True, upload_to='')),
                ('emailId', models.EmailField(default='xyz@gmail.com', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, null=True)),
                ('lastname', models.CharField(max_length=50, null=True)),
                ('Username', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(blank=True, default='xyz', max_length=50, null=True)),
                ('confirmPassword', models.CharField(blank=True, default='xyz', max_length=50, null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('pincode', models.IntegerField()),
                ('profileImg', models.FileField(null=True, upload_to='')),
                ('emailId', models.EmailField(default='xyz@gmail.com', max_length=254)),
            ],
        ),
    ]
